# Generated by Django 5.2 on 2025-09-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orthogram_number', models.IntegerField(verbose_name='Номер орфограммы')),
                ('correct_word', models.CharField(max_length=255, verbose_name='Правильное слово')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Правильный ответ',
                'verbose_name_plural': 'Правильные ответы',
            },
        ),
    ]
