# Generated by Django 5.2 on 2025-09-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_correctanswer'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='correctanswer',
            index=models.Index(fields=['orthogram_number'], name='orfo_num_idx'),
        ),
        migrations.AddIndex(
            model_name='correctanswer',
            index=models.Index(fields=['correct_word'], name='word_idx'),
        ),
        migrations.AddIndex(
            model_name='correctanswer',
            index=models.Index(fields=['orthogram_number', 'correct_word'], name='orfo_word_idx'),
        ),
    ]
