# Generated by Django 5.2 on 2025-10-14 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_orthogram_prepositionalphrase_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentorthogramprogress',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentorthogramprogress',
            name='orthogram',
        ),
        migrations.CreateModel(
            name='OrthogramExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('incorrect_variant', models.CharField(blank=True, max_length=300, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('is_for_quiz', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orthogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='main.orthogram')),
            ],
        ),
        migrations.DeleteModel(
            name='PrepositionalPhrase',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentOrthogramProgress',
        ),
    ]
