# Generated by Django 5.2 on 2025-10-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_student_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orthogram',
            name='grades',
            field=models.CharField(blank=True, help_text='Через запятую: 5,6,7', max_length=50),
        ),
    ]
