# Generated by Django 5.2 on 2025-10-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_orthogram_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='orthogramexample',
            name='grades',
            field=models.CharField(blank=True, help_text='Через запятую: 5,6,7', max_length=50),
        ),
    ]
