# Generated by Django 5.2 on 2025-10-15 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_orthogramexample_grades'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=300, verbose_name='Выбранный ответ')),
                ('is_correct', models.BooleanField(verbose_name='Правильно?')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда ответил')),
                ('orthogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orthogram', verbose_name='Орфограмма')),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orthogramexample', verbose_name='Пример')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ ученика',
                'verbose_name_plural': 'Ответы учеников',
            },
        ),
    ]
