# Generated by Django 5.2 on 2025-10-15 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orthogramexample',
            name='correct_word',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orthogramexample',
            name='orthogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orthogram'),
        ),
    ]
