# Generated by Django 5.2 on 2025-10-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_orthogramexample_correct_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orthogram',
            name='letters',
            field=models.CharField(default='а,о,е,и,я', help_text='Буквы или символы через запятую: а,б,в,г,д,е,ё,ж,з,и,й,к,л,м,н,о,п,р,с,т,у,ф,х,ц,ч,ш,щ,ъ,ы,ь,э,ю,я,-,/,|', max_length=200),
        ),
    ]
