# Generated by Django 5.2 on 2025-10-15 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_orthogram_letters'),
    ]

    operations = [
        migrations.AddField(
            model_name='orthogramexample',
            name='masked_word',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orthogramexample',
            name='orthogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='main.orthogram'),
        ),
    ]
