# Generated by Django 5.2 on 2025-10-15 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_orthogramexample_masked_word_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orthogramexample',
            name='correct_word',
        ),
    ]
