# Generated by Django 5.2 on 2025-10-16 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_orthogramexample_correct_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orthogramexample',
            name='orthogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orthogram'),
        ),
    ]
