# Generated by Django 5.2 on 2025-11-13 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_userprofile_telegram_id_alter_orthogram_letters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orthogramexample',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кем добавлен'),
        ),
        migrations.AddField(
            model_name='orthogramexample',
            name='is_user_added',
            field=models.BooleanField(default=False, verbose_name='Добавлен пользователем'),
        ),
        migrations.AddField(
            model_name='orthogramexample',
            name='source_field',
            field=models.CharField(blank=True, max_length=100, verbose_name='Поле-источник (например, user-input-orf-711)'),
        ),
    ]
