# Generated by Django 5.2 on 2025-12-04 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_orthogramexample_added_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orthogram',
            name='letters',
            field=models.CharField(default='а,о,е,и,я', help_text='Буквы или символы через запятую: а,б,в,г,д,е,ё,ж,з,и,й,к,л,м,н,о,п,р,с,т,у,ф,х,ц,ч,ш,щ,ъ,ы,ь,э,ю,я,-,/,\\,|,_', max_length=200),
        ),
        migrations.CreateModel(
            name='PunktumExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('masked_word', models.CharField(max_length=300)),
                ('explanation', models.TextField(blank=True, help_text='Правильные ответы через запятую: !, ?')),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_user_added', models.BooleanField(default=False, verbose_name='Добавлен пользователем')),
                ('source_field', models.CharField(blank=True, max_length=100, verbose_name='Поле-источник (например, user-input-orf-711)')),
                ('grades', models.CharField(blank=True, help_text='Через запятую: 5,6,7', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кем добавлен')),
            ],
        ),
    ]
