# Generated by Django 5.2 on 2025-12-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_orthogram_letters_punktumexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punktum',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('rule', models.TextField()),
                ('letters', models.CharField(default='!, ?', help_text='Символы через запятую: !, ?, -, (, ), [, ]', max_length=200)),
                ('grades', models.CharField(blank=True, help_text='Через запятую: 5,6,7', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
