# Generated by Django 5.2 on 2025-12-04 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_punktum'),
    ]

    operations = [
        migrations.AddField(
            model_name='punktumexample',
            name='punktum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.punktum'),
        ),
    ]
