# Generated by Django 5.2 on 2025-12-08 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_punktumexample_punktum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punktumexample',
            name='punktum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.punktum'),
            preserve_default=False,
        ),
    ]
