# Generated by Django 5.2 on 2025-12-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_punktumexample_punktum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punktumexample',
            name='masked_word',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='punktumexample',
            name='text',
            field=models.TextField(),
        ),
    ]
