# Generated by Django 5.2 on 2025-12-10 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_punktumexample_masked_word_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('text_content', models.TextField(verbose_name='Текст')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Автор')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Источник')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Текст для анализа',
                'verbose_name_plural': 'Тексты для анализа',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('missing_word', 'Подобрать слово'), ('multiple_choice', 'Множественный выбор'), ('text_characteristics', 'Характеристики текста')], max_length=50)),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('question_number', models.IntegerField(verbose_name='Номер вопроса (1, 2, 3)')),
                ('correct_answer', models.TextField(verbose_name='Правильный ответ')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.textanalysistask')),
            ],
            options={
                'verbose_name': 'Вопрос к тексту',
                'verbose_name_plural': 'Вопросы к тексту',
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField(verbose_name='Текст варианта')),
                ('option_number', models.IntegerField(verbose_name='Номер варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.textquestion')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['option_number'],
            },
        ),
    ]
