# Generated by Django 5.2 on 2025-12-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_textanalysistask_textquestion_questionoption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textanalysistask',
            options={'ordering': ['order'], 'verbose_name': 'Текст для анализа 1-3', 'verbose_name_plural': 'Тексты для анализа 1-3'},
        ),
        migrations.CreateModel(
            name='OrthoepyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_base', models.CharField(max_length=100, verbose_name='Базовая форма слова')),
                ('correct_variant', models.CharField(max_length=100, verbose_name='Правильный вариант с ударением')),
                ('incorrect_variants', models.CharField(max_length=500, verbose_name='Неправильные варианты с ударением через запятую')),
                ('explanation', models.TextField(blank=True, verbose_name='Объяснение')),
                ('difficulty', models.IntegerField(choices=[(1, 'Легкий'), (2, 'Средний'), (3, 'Сложный')], default=1, verbose_name='Сложность (1-3)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_for_quiz', models.BooleanField(default=False, help_text='Если отмечено, слово будет использоваться в квизах', verbose_name='Использовать в квизах')),
            ],
            options={
                'verbose_name': 'Слово для орфоэпии',
                'verbose_name_plural': 'Слова для орфоэпии',
                'ordering': ['word_base'],
                'indexes': [models.Index(fields=['word_base'], name='main_orthoe_word_ba_2ed581_idx'), models.Index(fields=['difficulty'], name='main_orthoe_difficu_765a7c_idx'), models.Index(fields=['is_for_quiz'], name='main_orthoe_is_for__42fa17_idx')],
            },
        ),
    ]
