# Generated by Django 5.2 on 2025-12-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_textanalysistask_options_orthoepyword'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orthoepyword',
            name='main_orthoe_difficu_765a7c_idx',
        ),
        migrations.RemoveField(
            model_name='orthoepyword',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='orthoepyword',
            name='explanation',
        ),
        migrations.AddField(
            model_name='orthoepyword',
            name='grades',
            field=models.CharField(blank=True, help_text='Через запятую: 5,6,7,8,9,10,11 или оставить пустым для всех', max_length=50, verbose_name='Для классов'),
        ),
        migrations.AddIndex(
            model_name='orthoepyword',
            index=models.Index(fields=['grades'], name='main_orthoe_grades_7f2e5a_idx'),
        ),
    ]
