# Generated by Django 5.2 on 2025-12-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_orthoepyword_main_orthoe_difficu_765a7c_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orthoepyword',
            options={'ordering': ['correct_variant'], 'verbose_name': 'Слово для орфоэпии', 'verbose_name_plural': 'Слова для орфоэпии'},
        ),
        migrations.RemoveIndex(
            model_name='orthoepyword',
            name='main_orthoe_word_ba_2ed581_idx',
        ),
        migrations.RemoveIndex(
            model_name='orthoepyword',
            name='main_orthoe_is_for__42fa17_idx',
        ),
        migrations.RemoveIndex(
            model_name='orthoepyword',
            name='main_orthoe_grades_7f2e5a_idx',
        ),
        migrations.RemoveField(
            model_name='orthoepyword',
            name='word_base',
        ),
        migrations.AlterField(
            model_name='orthoepyword',
            name='correct_variant',
            field=models.CharField(help_text='Пример: бралА, бАнты, аэропОрты', max_length=100, unique=True, verbose_name='Слово с правильным ударением'),
        ),
        migrations.AlterField(
            model_name='orthoepyword',
            name='grades',
            field=models.CharField(blank=True, help_text='Через запятую: 9,10,11 или оставить пустым для всех', max_length=50, verbose_name='Для классов'),
        ),
        migrations.AlterField(
            model_name='orthoepyword',
            name='incorrect_variants',
            field=models.CharField(help_text='Пример: брАла, бантЫ, аэропортЫ', max_length=500, verbose_name='Неправильные варианты через запятую'),
        ),
        migrations.AlterField(
            model_name='orthoepyword',
            name='is_for_quiz',
            field=models.BooleanField(default=False, help_text='Если отмечено, слово будет использоваться в тестах', verbose_name='Использовать в тестах'),
        ),
    ]
