# Generated by Django 5.2 on 2025-12-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_orthoepyword_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orthoepyword',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Если отмечено, слово будет использоваться в тестах', verbose_name='Активно (для тестов)'),
        ),
        migrations.AlterField(
            model_name='orthoepyword',
            name='is_for_quiz',
            field=models.BooleanField(default=False, help_text='Использовать в квизах (будущая функциональность)', verbose_name='Для квизов'),
        ),
    ]
