# Generated by Django 5.2 on 2025-12-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_orthoepyword_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orthoepyword',
            name='correct_variant',
            field=models.CharField(max_length=100, unique=True, verbose_name='Слово с правильным ударением'),
        ),
        migrations.AlterField(
            model_name='orthoepyword',
            name='grades',
            field=models.CharField(blank=True, max_length=50, verbose_name='Классы'),
        ),
        migrations.AlterField(
            model_name='orthoepyword',
            name='incorrect_variants',
            field=models.CharField(blank=True, max_length=500, verbose_name='Неправильные варианты'),
        ),
        migrations.AlterField(
            model_name='orthoepyword',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='orthoepyword',
            name='is_for_quiz',
            field=models.BooleanField(default=False, help_text='Используется в будущих квизах (не в основном тесте)', verbose_name='Для квизов'),
        ),
    ]
