# Generated by Django 5.2 on 2025-12-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_orthoepyword_correct_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incorrect_text', models.CharField(help_text='Пример: сожгет, чулков, замрзнул', max_length=200, verbose_name='Неправильный текст (с ошибкой)')),
                ('correct_text', models.CharField(help_text='Пример: сожжет, чулок, замерз', max_length=200, verbose_name='Правильный текст')),
                ('explanation', models.CharField(blank=True, max_length=300, verbose_name='Пояснение')),
                ('exercise_id', models.CharField(default='711', max_length=20, verbose_name='ID задания')),
                ('grades', models.CharField(blank=True, max_length=50, verbose_name='Классы (через запятую)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_for_quiz', models.BooleanField(default=False, help_text='Использовать в квизах', verbose_name='Для квизов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Упражнение: исправь ошибку',
                'verbose_name_plural': 'Упражнения: исправь ошибку',
            },
        ),
    ]
