# Generated by Django 5.2 on 2025-12-17 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_correctionexercise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correctionexercise',
            options={'verbose_name': 'ЗАДАНИЕ 7: исправь ошибку', 'verbose_name_plural': 'ЗАДАНИЕ 7: исправь ошибку'},
        ),
    ]
