# Generated by Django 5.2 on 2025-12-22 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_correctionexercise_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGrammaticEight',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('letter', models.CharField(choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г'), ('Д', 'Д')], max_length=1, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('rule', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Тип ошибки (задание 8)',
                'verbose_name_plural': 'Типы ошибок (задание 8)',
            },
        ),
        migrations.CreateModel(
            name='TaskGrammaticEightExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('has_error', models.BooleanField(default=True)),
                ('explanation', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_for_quiz', models.BooleanField(default=True)),
                ('grades', models.CharField(blank=True, max_length=50)),
                ('error_type', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.taskgrammaticeight')),
            ],
            options={
                'verbose_name': 'Пример для задания 8',
                'verbose_name_plural': 'Примеры для задания 8',
            },
        ),
    ]
