# Generated by Django 5.2 on 2025-12-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_taskgrammaticeight_taskgrammaticeightexample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskgrammaticeight',
            name='name',
        ),
        migrations.RemoveField(
            model_name='taskgrammaticeight',
            name='rule',
        ),
        migrations.AlterField(
            model_name='taskgrammaticeight',
            name='id',
            field=models.CharField(choices=[('8100', 'Нарушение в построении предложения с подлежащим и сказуемым'), ('8200', 'Ошибка в построении предложения с причастным оборотом'), ('8300', 'Ошибка в построении предложения с деепричастным оборотом'), ('8400', 'Нарушение в построении предложения с однородными членами'), ('8500', 'Нарушение видо-временной соотнесённости глагольных форм'), ('8600', 'Нарушение в построении предложения с приложением'), ('8700', 'Нарушение в управлении (предлог + падеж)'), ('8800', 'Ошибка в построении предложения с косвенной речью'), ('8900', 'Нарушение в построении сложного предложения'), ('8910', 'Нарушение в употреблении числительного')], max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taskgrammaticeight',
            name='letter',
            field=models.CharField(blank=True, choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г'), ('Д', 'Д')], max_length=1, null=True, unique=True),
        ),
    ]
