# Generated by Django 5.2 on 2025-12-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remove_taskgrammaticeight_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskgrammaticeight',
            name='letter',
        ),
        migrations.AlterField(
            model_name='taskgrammaticeightexample',
            name='is_for_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
