# Generated by Django 5.2 on 2025-12-23 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_taskgrammaticeight_letter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGrammaticTwoTwo',
            fields=[
                ('id', models.CharField(choices=[('2201', 'метафора'), ('2202', 'метонимия'), ('2203', 'синекдоха'), ('2204', 'эпитет'), ('2205', 'сравнение'), ('2206', 'гипербола'), ('2207', 'литота'), ('2208', 'аллегория'), ('2209', 'олицетворение'), ('2210', 'параллелизм'), ('2211', 'антитеза'), ('2212', 'инверсия'), ('2213', 'анафора'), ('2214', 'эпифора'), ('2215', 'градация'), ('2216', 'оксюморон'), ('2217', 'риторическое обращение'), ('2218', 'риторический вопрос'), ('2219', 'парцелляция'), ('2220', 'эллипсис'), ('2221', 'умолчание'), ('2222', 'лексический повтор'), ('2223', 'синтаксический параллелизм'), ('2224', 'многосоюзие'), ('2225', 'бессоюзие'), ('2226', 'каламбур'), ('2227', 'ирония'), ('2228', 'сарказм'), ('2229', 'плеоназм'), ('2230', 'тавтология'), ('2231', 'символ'), ('2232', 'гротеск'), ('2233', 'аллюзия'), ('2234', 'аллегория'), ('2235', 'перифраза')], max_length=10, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Средство выразительности (задание 22)',
                'verbose_name_plural': 'Средства выразительности (задание 22)',
            },
        ),
        migrations.CreateModel(
            name='TaskGrammaticTwoTwoExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_for_quiz', models.BooleanField(default=False)),
                ('grades', models.CharField(blank=True, max_length=50)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('device_type', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.taskgrammatictwotwo')),
            ],
            options={
                'verbose_name': 'Пример для задания 22',
                'verbose_name_plural': 'Примеры для задания 22',
            },
        ),
    ]
