# Generated by Django 5.2 on 2025-12-25 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_taskgrammatictwotwo_taskgrammatictwotwoexample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskgrammatictwotwoexample',
            name='device_type',
        ),
        migrations.AddField(
            model_name='taskgrammatictwotwoexample',
            name='device',
            field=models.ForeignKey(default=2201, on_delete=django.db.models.deletion.CASCADE, related_name='related_examples', to='main.taskgrammatictwotwo', verbose_name='Средство выразительности'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskgrammatictwotwoexample',
            name='author',
            field=models.CharField(blank=True, max_length=200, verbose_name='Автор (опционально)'),
        ),
        migrations.AlterField(
            model_name='taskgrammatictwotwoexample',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Пояснение'),
        ),
        migrations.AlterField(
            model_name='taskgrammatictwotwoexample',
            name='grades',
            field=models.CharField(blank=True, max_length=50, verbose_name='Классы'),
        ),
        migrations.AlterField(
            model_name='taskgrammatictwotwoexample',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='taskgrammatictwotwoexample',
            name='is_for_quiz',
            field=models.BooleanField(default=False, verbose_name='Использовать в тестах'),
        ),
        migrations.AlterField(
            model_name='taskgrammatictwotwoexample',
            name='text',
            field=models.TextField(verbose_name='Пример из текста'),
        ),
    ]
