# Generated by Django 5.2 on 2025-12-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_taskgrammatictwotwoexample_device_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPaponim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Выделите слово жирным, используя **двойные звёздочки**: ...**гарантийного**...', verbose_name='Предложение с выделенным словом')),
                ('correct_word', models.CharField(blank=True, default='', max_length=100, verbose_name='Правильное слово (пароним)')),
                ('root', models.CharField(blank=True, default='', help_text="Примеры: 'деть', 'гарант', 'абон'", max_length=50, verbose_name='Корень (для исключения в одном тесте)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_for_quiz', models.BooleanField(default=False, verbose_name='Использовать в квизах')),
                ('grades', models.CharField(blank=True, default='', max_length=50, verbose_name='Классы')),
            ],
            options={
                'verbose_name': 'ПАРОНИМЫ задание 5',
                'verbose_name_plural': 'ПАРОНИМЫ задание 5',
            },
        ),
    ]
