# Generated by Django 5.2 on 2025-12-25 23:12
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('main', '0041_taskpaponim'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpaponim',
            name='root',
            field=models.CharField(
                max_length=50,
                blank=True,
                default='',
                verbose_name="Корень (для исключения в одном тесте)",
                help_text="Примеры: 'деть', 'гарант', 'абон'"
            ),
        ),
    ]