# Generated by Django 5.2 on 2025-12-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20251226_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordOk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Предложение с лексической ошибкой')),
                ('task_type', models.CharField(choices=[('6100', 'Исключить лишнее слово'), ('6200', 'Заменить неверное слово')], max_length=4, verbose_name='Тип задания')),
                ('correct_variants', models.TextField(help_text='Для 6100 — одно слово. Для 6200 — варианты: одержать,совершить,добиться', verbose_name='Правильные слова (через запятую, без пробелов)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_for_quiz', models.BooleanField(default=False, verbose_name='Использовать в квизах')),
                ('grades', models.CharField(blank=True, max_length=50, verbose_name='Классы')),
            ],
            options={
                'verbose_name': 'Задание 6: Лексические нормы',
                'verbose_name_plural': 'Задание 6: Лексические нормы',
            },
        ),
    ]
