# Generated by Django 5.2 on 2026-01-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_wordok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textquestion',
            name='question_type',
            field=models.CharField(choices=[('missing_word', 'Подобрать слово'), ('multiple_choice', 'Множественный выбор'), ('text_characteristics', 'Характеристики текста'), ('free_text', 'Свободный текст (выписать из текста)')], max_length=50),
        ),
    ]
