# Generated by Django 5.2 on 2026-01-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_textquestion_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orthogramexample',
            name='correct_letters',
            field=models.CharField(blank=True, max_length=100, verbose_name='Правильные буквы (через запятую)'),
        ),
    ]
