# Generated by Django 5.2 on 2026-01-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_orthogramexample_correct_letters'),
    ]

    operations = [
        migrations.AddField(
            model_name='punktumexample',
            name='correct_letters',
            field=models.CharField(blank=True, max_length=100, verbose_name='Правильные символы пунктуации (через запятую)'),
        ),
    ]
