# Generated by Django 5.2 on 2026-02-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_taskgrammatictwotwo_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orthoepyword',
            options={'ordering': ['word'], 'verbose_name': 'Слово для орфоэпии', 'verbose_name_plural': 'Слова для орфоэпии'},
        ),
        migrations.RemoveField(
            model_name='orthoepyword',
            name='correct_variant',
        ),
        migrations.RemoveField(
            model_name='orthoepyword',
            name='incorrect_variants',
        ),
        migrations.RemoveField(
            model_name='orthoepyword',
            name='is_for_quiz',
        ),
        migrations.AddField(
            model_name='orthoepyword',
            name='is_correct',
            field=models.BooleanField(default=True, help_text='✓ — правильное, ✗ — неправильное', verbose_name='Правильное ударение'),
        ),
        migrations.AddField(
            model_name='orthoepyword',
            name='word',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Слово с ударением'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orthoepyword',
            name='grades',
            field=models.CharField(blank=True, help_text='Например: 5,6,7', max_length=50, verbose_name='Классы'),
        ),
    ]
