# Generated by Django 5.2 on 2026-02-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_orthoepyword_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orthoepyword',
            name='lemma',
            field=models.CharField(default='', help_text='Например: аэропорты, баловать', max_length=100, verbose_name='Лемма (слово без ударения)'),
            preserve_default=False,
        ),
    ]
