# Generated by Django 5.2 on 2026-02-21 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_orthoepyword_lemma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OgeCorrectionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incorrect_text', models.CharField(max_length=200, verbose_name='Неправильный текст (с ошибкой)')),
                ('correct_text', models.CharField(max_length=200, verbose_name='Правильный текст')),
                ('explanation', models.CharField(blank=True, max_length=300, verbose_name='Пояснение')),
                ('exercise_id', models.CharField(default='711', max_length=20, verbose_name='ID задания')),
                ('grades', models.CharField(blank=True, max_length=50, verbose_name='Классы (через запятую)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_for_quiz', models.BooleanField(default=False, verbose_name='Для квизов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ОГЭ: Задание 7 — исправь ошибку',
                'verbose_name_plural': 'ОГЭ: Задание 7 — исправь ошибку',
            },
        ),
        migrations.CreateModel(
            name='OgeOrthogram',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('rule', models.TextField()),
                ('letters', models.CharField(default='а,о,е,и,я', help_text='Буквы через запятую', max_length=200)),
                ('grades', models.CharField(blank=True, help_text='Через запятую: 5,6,7', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ОГЭ: Орфограмма (задание 6)',
                'verbose_name_plural': 'ОГЭ: Орфограммы (задание 6)',
            },
        ),
        migrations.CreateModel(
            name='OgePunktum',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('rule', models.TextField()),
                ('letters', models.CharField(default='!, ?, —, :, «»', help_text='Символы через запятую: !, ?, —, :, «» (кавычки)', max_length=200)),
                ('grades', models.CharField(blank=True, help_text='Через запятую: 5,6,7', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ОГЭ: Пунктограмма (задание 4)',
                'verbose_name_plural': 'ОГЭ: Пунктограммы (задание 4)',
            },
        ),
        migrations.CreateModel(
            name='OgeTaskGrammaticEight',
            fields=[
                ('id', models.CharField(choices=[('8100', 'Нарушение в построении предложения с подлежащим и сказуемым'), ('8200', 'Ошибка в построении предложения с причастным оборотом'), ('8300', 'Ошибка в построении предложения с деепричастным оборотом'), ('8400', 'Нарушение в построении предложения с однородными членами'), ('8500', 'Нарушение видо-временной соотнесённости глагольных форм'), ('8600', 'Нарушение в построении предложения с приложением'), ('8700', 'Нарушение в управлении (предлог + падеж)'), ('8800', 'Ошибка в построении предложения с косвенной речью'), ('8900', 'Нарушение в построении сложного предложения'), ('8910', 'Нарушение в употреблении числительного')], max_length=10, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ОГЭ: Тип ошибки (задание 3)',
                'verbose_name_plural': 'ОГЭ: Типы ошибок (задание 3)',
            },
        ),
        migrations.CreateModel(
            name='OgeTextAnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('text_content', models.TextField(verbose_name='Текст')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Автор')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Источник')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'ОГЭ: Текст для анализа',
                'verbose_name_plural': 'ОГЭ: Тексты для анализа',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OgeWordOk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Предложение с лексической ошибкой')),
                ('task_type', models.CharField(choices=[('6100', 'Исключить лишнее слово'), ('6200', 'Заменить неверное слово')], max_length=4, verbose_name='Тип задания')),
                ('correct_variants', models.TextField(help_text='Для 6100 — одно слово. Для 6200 — варианты: одержать,совершить', verbose_name='Правильные слова (через запятую)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_for_quiz', models.BooleanField(default=False, verbose_name='Для квизов')),
                ('grades', models.CharField(blank=True, max_length=50, verbose_name='Классы')),
            ],
            options={
                'verbose_name': 'ОГЭ: Задание 8 — лексические нормы',
                'verbose_name_plural': 'ОГЭ: Задание 8 — лексические нормы',
            },
        ),
        migrations.CreateModel(
            name='OgeOrthogramExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('masked_word', models.CharField(max_length=300)),
                ('incorrect_variant', models.CharField(blank=True, max_length=300, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('correct_letters', models.CharField(blank=True, max_length=100, verbose_name='Правильные буквы (через запятую)')),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('is_for_quiz', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_user_added', models.BooleanField(default=False, verbose_name='Добавлен пользователем')),
                ('source_field', models.CharField(blank=True, max_length=100, verbose_name='Поле-источник')),
                ('grades', models.CharField(blank=True, help_text='Через запятую: 5,6,7', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кем добавлен')),
                ('orthogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ogeorthogram')),
            ],
            options={
                'verbose_name': 'ОГЭ: Пример орфограммы (задание 6)',
                'verbose_name_plural': 'ОГЭ: Примеры орфограмм (задание 6)',
            },
        ),
        migrations.CreateModel(
            name='OgePunktumExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('masked_word', models.TextField()),
                ('explanation', models.TextField(blank=True, help_text='Правильные ответы через запятую: !, ?, «»')),
                ('correct_letters', models.CharField(blank=True, max_length=100, verbose_name='Правильные символы пунктуации (через запятую)')),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_user_added', models.BooleanField(default=False, verbose_name='Добавлен пользователем')),
                ('source_field', models.CharField(blank=True, max_length=100, verbose_name='Поле-источник')),
                ('grades', models.CharField(blank=True, help_text='Через запятую: 5,6,7', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кем добавлен')),
                ('punktum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ogepunktum')),
            ],
            options={
                'verbose_name': 'ОГЭ: Пример пунктуации (задание 4)',
                'verbose_name_plural': 'ОГЭ: Примеры пунктуации (задание 4)',
            },
        ),
        migrations.CreateModel(
            name='OgeTaskGrammaticEightExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('has_error', models.BooleanField(default=True)),
                ('explanation', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_for_quiz', models.BooleanField(default=False)),
                ('grades', models.CharField(blank=True, max_length=50)),
                ('error_type', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ogetaskgrammaticeight')),
            ],
            options={
                'verbose_name': 'ОГЭ: Пример для задания 3',
                'verbose_name_plural': 'ОГЭ: Примеры для задания 3',
            },
        ),
        migrations.CreateModel(
            name='OgeTextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('missing_word', 'Подобрать слово'), ('multiple_choice', 'Множественный выбор'), ('text_characteristics', 'Характеристики текста'), ('free_text', 'Свободный текст (выписать из текста)')], max_length=50)),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('question_number', models.IntegerField(verbose_name='Номер вопроса (1–11)')),
                ('correct_answer', models.TextField(verbose_name='Правильный ответ')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.ogetextanalysistask')),
            ],
            options={
                'verbose_name': 'ОГЭ: Вопрос к тексту',
                'verbose_name_plural': 'ОГЭ: Вопросы к тексту',
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='OgeQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField(verbose_name='Текст варианта')),
                ('option_number', models.IntegerField(verbose_name='Номер варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.ogetextquestion')),
            ],
            options={
                'verbose_name': 'ОГЭ: Вариант ответа',
                'verbose_name_plural': 'ОГЭ: Варианты ответов',
                'ordering': ['option_number'],
            },
        ),
    ]
