# Generated by Django 5.2 on 2026-02-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_ogecorrectionexercise_ogeorthogram_ogepunktum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogequestionoption',
            name='orthogram_numbers',
            field=models.CharField(blank=True, max_length=255, verbose_name='№№ орфограмм (для ответа)'),
        ),
    ]
