# Generated by Django 5.2 on 2026-02-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_ogequestionoption_orthogram_numbers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ogetaskgrammaticeight',
            options={'verbose_name': 'ОГЭ: Пунктуационное правило (задание 4)', 'verbose_name_plural': 'ОГЭ: Пунктуационные правила (задание 4)'},
        ),
        migrations.AlterField(
            model_name='ogetaskgrammaticeight',
            name='id',
            field=models.CharField(choices=[('8100', 'В неполном предложении на месте пропуска члена предложения ставится тире.'), ('8200', 'Между подлежащим и сказуемым, выраженными именами существительными в именительном падеже, при нулевой связке ставится тире.'), ('8300', 'Обстоятельство, выраженное деепричастным оборотом, обособляется.'), ('8400', 'Определение, выраженное причастным оборотом, стоящее после определяемого слова, обособляется.'), ('8500', 'Вводное слово выделяется запятыми.')], max_length=10, primary_key=True, serialize=False),
        ),
    ]
