# Generated by Django 5.2 on 2026-02-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_ogetaskgrammaticeight_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correctionexercise',
            options={'verbose_name': 'ЗАДАНИЕ 8: исправь ошибку', 'verbose_name_plural': 'ЗАДАНИЕ 8: исправь ошибку'},
        ),
        migrations.AlterModelOptions(
            name='ogecorrectionexercise',
            options={'verbose_name': 'ОГЭ: Задание 8 — исправь ошибку', 'verbose_name_plural': 'ОГЭ: Задание 8 — исправь ошибку'},
        ),
        migrations.AlterModelOptions(
            name='ogeorthogram',
            options={'verbose_name': 'ОГЭ: Орфограмма (задание 7)', 'verbose_name_plural': 'ОГЭ: Орфограммы (задание 7)'},
        ),
        migrations.AlterModelOptions(
            name='ogeorthogramexample',
            options={'verbose_name': 'ОГЭ: Пример орфограммы (задание 7)', 'verbose_name_plural': 'ОГЭ: Примеры орфограмм (задание 7)'},
        ),
        migrations.AlterModelOptions(
            name='ogepunktum',
            options={'verbose_name': 'ОГЭ: Пунктограмма (задание 5)', 'verbose_name_plural': 'ОГЭ: Пунктограммы (задание 5)'},
        ),
        migrations.AlterModelOptions(
            name='ogepunktumexample',
            options={'verbose_name': 'ОГЭ: Пример пунктуации (задание 5)', 'verbose_name_plural': 'ОГЭ: Примеры пунктуации (задание 5)'},
        ),
        migrations.AlterModelOptions(
            name='ogetaskgrammaticeight',
            options={'verbose_name': 'ОГЭ: Пунктуационное правило (задание 5)', 'verbose_name_plural': 'ОГЭ: Пунктуационные правила (задание 5)'},
        ),
        migrations.AlterModelOptions(
            name='ogetaskgrammaticeightexample',
            options={'verbose_name': 'ОГЭ: Пример для задания 4', 'verbose_name_plural': 'ОГЭ: Примеры для задания 4'},
        ),
        migrations.AlterModelOptions(
            name='ogewordok',
            options={'verbose_name': 'ОГЭ: Задание 9 — лексические нормы', 'verbose_name_plural': 'ОГЭ: Задание 9 — лексические нормы'},
        ),
        migrations.AlterModelOptions(
            name='taskgrammaticeight',
            options={'verbose_name': 'Тип ошибки (задание 9)', 'verbose_name_plural': 'Типы ошибок (задание 9)'},
        ),
        migrations.AlterModelOptions(
            name='taskgrammaticeightexample',
            options={'verbose_name': 'Пример для задания 9', 'verbose_name_plural': 'Примеры для задания 9'},
        ),
        migrations.AlterModelOptions(
            name='taskgrammatictwotwo',
            options={'verbose_name': 'Средство выразительности (задание 23)', 'verbose_name_plural': 'Средства выразительности (задание 23)'},
        ),
        migrations.AlterModelOptions(
            name='taskgrammatictwotwoexample',
            options={'verbose_name': 'Пример для задания 23', 'verbose_name_plural': 'Примеры для задания 23'},
        ),
        migrations.AlterModelOptions(
            name='taskpaponim',
            options={'verbose_name': 'ПАРОНИМЫ задание 6', 'verbose_name_plural': 'ПАРОНИМЫ задание 6'},
        ),
        migrations.AlterModelOptions(
            name='textanalysistask',
            options={'ordering': ['order'], 'verbose_name': 'Текст для анализа 2-4', 'verbose_name_plural': 'Тексты для анализа 2-4'},
        ),
        migrations.AlterModelOptions(
            name='wordok',
            options={'verbose_name': 'Задание 7: Лексические нормы', 'verbose_name_plural': 'Задание 7: Лексические нормы'},
        ),
        migrations.AlterField(
            model_name='ogetextquestion',
            name='question_number',
            field=models.IntegerField(verbose_name='Номер вопроса (2–12)'),
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='question_number',
            field=models.IntegerField(verbose_name='Номер вопроса (2, 3, 4)'),
        ),
    ]
