# Generated by Django 5.2 on 2026-02-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_correctionexercise_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correctionexercise',
            options={'verbose_name': 'ЗАДАНИЕ 7: исправь ошибку', 'verbose_name_plural': 'ЗАДАНИЕ 7: исправь ошибку'},
        ),
        migrations.AlterModelOptions(
            name='taskgrammaticeight',
            options={'verbose_name': 'Тип ошибки (задание 8)', 'verbose_name_plural': 'Типы ошибок (задание 8)'},
        ),
        migrations.AlterModelOptions(
            name='taskgrammaticeightexample',
            options={'verbose_name': 'Пример для задания 8', 'verbose_name_plural': 'Примеры для задания 8'},
        ),
        migrations.AlterModelOptions(
            name='taskpaponim',
            options={'verbose_name': 'ПАРОНИМЫ задание 5', 'verbose_name_plural': 'ПАРОНИМЫ задание 5'},
        ),
        migrations.AlterModelOptions(
            name='wordok',
            options={'verbose_name': 'Задание 6: Лексические нормы', 'verbose_name_plural': 'Задание 6: Лексические нормы'},
        ),
    ]
