# Generated by Django 5.2 on 2026-03-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_correctionexercise_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogepunktumexample',
            name='is_for_quiz',
            field=models.BooleanField(default=True, verbose_name='Использовать в квизах'),
        ),
    ]
