# Generated by Django 5.2 on 2026-03-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_ogepunktumexample_is_for_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogetaskgrammaticeight',
            name='name',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Описание правила'),
        ),
        migrations.AlterField(
            model_name='ogetaskgrammaticeight',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
