# Generated by Django 5.2 on 2026-03-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_ogetaskgrammaticeight_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ogepunktum',
            options={'verbose_name': 'ТРЕНАЖЕРЫ 9кл 5 зад', 'verbose_name_plural': 'ТРЕНАЖЕРЫ 9кл 5 зад'},
        ),
        migrations.AddField(
            model_name='ogepunktumexample',
            name='choices_per_mask',
            field=models.TextField(blank=True, help_text='Формат: correct1|opt1/opt2/opt3,correct2|opt1/opt2 — по одной позиции на маску', verbose_name='Варианты по позициям (correct|opt1/opt2/opt3,...)'),
        ),
    ]
