# Generated by Django 5.2 on 2026-03-11 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_userword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userword',
            options={'verbose_name': 'Слово пользователя', 'verbose_name_plural': 'Слова пользователей'},
        ),
        migrations.RemoveField(
            model_name='userword',
            name='is_in_master_db',
        ),
        migrations.AddField(
            model_name='userword',
            name='in_master',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userword',
            name='field_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userword',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='userword',
            name='reference_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.orthogramexample'),
        ),
        migrations.AlterField(
            model_name='userword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userword',
            index=models.Index(fields=['user', 'in_master', 'is_active'], name='main_userwo_user_id_fc61e9_idx'),
        ),
    ]
