# Generated by Django 5.2 on 2026-03-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_userword_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userword',
            name='last_shown',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
