# Generated by Django 5.2 on 2026-03-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_userword_last_shown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userword',
            name='last_shown',
            field=models.DateTimeField(blank=True, help_text='Когда слово показывалось в квизе', null=True),
        ),
    ]
