# Generated by Django 5.2 on 2026-03-11 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_userword_last_shown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userword',
            name='error_count',
            field=models.IntegerField(default=0, help_text='Сколько раз ошиблись'),
        ),
        migrations.AddField(
            model_name='userword',
            name='last_error',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userword',
            name='success_count',
            field=models.IntegerField(default=0, help_text='Сколько раз ответили правильно'),
        ),
        migrations.AddField(
            model_name='userword',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userword',
            name='weight',
            field=models.FloatField(default=1.0, help_text='Вес слова (чем выше, тем чаще показывается)'),
        ),
        migrations.AlterField(
            model_name='userword',
            name='last_shown',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='userword',
            index=models.Index(fields=['user', 'weight'], name='main_userwo_user_id_c8aedb_idx'),
        ),
    ]
