# Generated by Django 5.2 on 2026-03-11 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_userword_error_count_userword_last_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_correct', models.BooleanField()),
                ('answer_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_history', to=settings.AUTH_USER_MODEL)),
                ('user_word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.userword')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orthogramexample')),
            ],
            options={
                'verbose_name': 'История квизов',
                'verbose_name_plural': 'История квизов',
                'ordering': ['-answer_time'],
                'indexes': [models.Index(fields=['user', '-answer_time'], name='main_quizhi_user_id_0b9e67_idx'), models.Index(fields=['user', 'was_correct'], name='main_quizhi_user_id_48e827_idx')],
            },
        ),
    ]
