# Generated by Django 5.2 on 2026-03-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_ogetaskgrammaticeight_name_and_more'),
        ('main', '0060_quizhistory'),
    ]

    operations = [
    ]
