# Generated by Django 5.2 on 2026-03-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_merge_20260312_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='link_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код привязки VK'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='link_code_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия кода'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vk_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='VK ID'),
        ),
    ]
