# Generated by Django 5.2 on 2026-08-02 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_userprofile_link_code_userprofile_link_code_expires_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskgrammatictwotwo',
            options={'verbose_name': 'Средство выразительности (задание 22)', 'verbose_name_plural': 'Средства выразительности (задание 22)'},
        ),
        migrations.AlterModelOptions(
            name='taskgrammatictwotwoexample',
            options={'verbose_name': 'Пример для задания 22', 'verbose_name_plural': 'Примеры для задания 22'},
        ),
        migrations.CreateModel(
            name='DiagnosticAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('access_code', models.CharField(blank=True, max_length=12, unique=True)),
                ('test_code', models.CharField(default='DIAG_EGE_2027_V1', max_length=50)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('max_score', models.IntegerField(default=50)),
                ('answers_data', models.JSONField(default=dict)),
                ('weak_topics', models.JSONField(default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
