# Generated by Django 5.2 on 2026-08-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_alter_taskgrammatictwotwo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticattempt',
            name='is_reviewed_by_teacher',
            field=models.BooleanField(default=False, verbose_name='Разобрано на встрече'),
        ),
        migrations.AddField(
            model_name='diagnosticattempt',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата разбора'),
        ),
        migrations.AddField(
            model_name='diagnosticattempt',
            name='teacher_notes',
            field=models.TextField(blank=True, verbose_name='Заметки преподавателя'),
        ),
    ]
