# Generated by Django 5.2 on 2026-08-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_diagnosticattempt_is_reviewed_by_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_month',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('free', '0'), ('self', 'Я сам'), ('group', 'Вместе'), ('premium', 'Премиум')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trial_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
