# Generated by Django 5.2 on 2026-08-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_userprofile_role_userprofile_tutor_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='MAX ID'),
        ),
    ]
