# Generated by Django 5.2 on 2026-08-11 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_userprofile_max_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField()),
                ('source', models.CharField(default='', max_length=20)),
                ('example_id', models.IntegerField(blank=True, null=True)),
                ('user_word_id', models.IntegerField(blank=True, null=True)),
                ('question', models.TextField(default='')),
                ('options_json', models.TextField(default='')),
                ('correct_text', models.CharField(default='', max_length=200)),
                ('explanation', models.TextField(default='')),
                ('answered', models.BooleanField(default=False)),
                ('answered_correctly', models.BooleanField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'period_date')},
            },
        ),
    ]
