# Generated by Django 5.2 on 2026-08-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_dailyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='MAX chat ID'),
        ),
    ]
