# Generated by Django 5.2 on 2026-08-12 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_userprofile_max_chat_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrthoepyAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_words', models.IntegerField(default=0)),
                ('chosen_count', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orthoepy_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrthoepyAttemptWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.IntegerField()),
                ('word', models.CharField(max_length=100)),
                ('chosen_index', models.IntegerField()),
                ('correct_index', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='main.orthoepyattempt')),
            ],
        ),
        migrations.CreateModel(
            name='OrthoepyWordStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.IntegerField()),
                ('word', models.CharField(max_length=100)),
                ('correct_index', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('last_result', models.BooleanField(null=True)),
                ('last_chosen_index', models.IntegerField(null=True)),
                ('last_seen', models.DateTimeField(null=True)),
                ('in_correction', models.BooleanField(default=False)),
                ('correction_since', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orthoepy_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'word_id')},
            },
        ),
    ]
