# Generated by Django 5.2 on 2026-08-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_essayscore_lessonview_paponimview'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticattempt',
            name='primary_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Первичный балл'),
        ),
        migrations.AlterField(
            model_name='essayscore',
            name='max_score',
            field=models.FloatField(default=22.0),
        ),
    ]
