# Generated by Django 5.2 on 2026-08-14 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='feedback',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AiQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('intent', models.CharField(blank=True, default='', max_length=50)),
                ('specialist', models.CharField(blank=True, default='', max_length=50)),
                ('reply', models.TextField(blank=True, default='')),
                ('guessed_word', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_logs', to='main.chatmessage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_query_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запрос к ИИ',
                'verbose_name_plural': 'Логи запросов к ИИ',
                'ordering': ['-created_at'],
            },
        ),
    ]
