# Generated by Django 5.2 on 2026-08-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_chatmessage_feedback_aiquerylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordok',
            name='explanation',
            field=models.TextField(blank=True, default='', help_text='Короткое объяснение, почему слово лишнее/неверное. Используется ИИ-ассистентом', verbose_name='Объяснение ошибки (для RAG)'),
        ),
    ]
