# Generated by Django 5.2 on 2026-08-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_wordok_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RagTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код темы')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('source', models.CharField(blank=True, default='', max_length=150, verbose_name='Источник данных')),
                ('is_ready', models.BooleanField(default=False, verbose_name='Готова отвечать')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тема RAG',
                'verbose_name_plural': 'Реестр тем RAG',
                'ordering': ['order'],
            },
        ),
    ]
