# Generated by Django 5.2 on 2026-08-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_llmcache_botlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnalysisTask2326',
            fields=[
            ],
            options={
                'verbose_name': 'Текст для анализа 23–26',
                'verbose_name_plural': 'Тексты для анализа 23–26',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.textanalysistask',),
        ),
        migrations.AlterModelOptions(
            name='textanalysistask',
            options={'ordering': ['order'], 'verbose_name': 'Текст для анализа 1–3', 'verbose_name_plural': 'Тексты для анализа 1–3'},
        ),
        migrations.AddField(
            model_name='textanalysistask',
            name='task_type',
            field=models.CharField(choices=[('1_3', 'Задания 1–3 (микротекст)'), ('23_26', 'Задания 23–26 (макротекст)')], db_index=True, default='1_3', help_text='Микротекст — задания 1–3, макротекст — задания 23–26', max_length=10, verbose_name='Тип текста'),
        ),
    ]
