# Generated by Django 5.2 on 2026-09-01 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_textanalysistask2326_alter_textanalysistask_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ogetaskgrammaticeight',
            options={'verbose_name': 'ОГЭ: Пунктуационное правило (задание 4)', 'verbose_name_plural': 'ОГЭ: Пунктуационные правила (задание 4)'},
        ),
    ]
