# Generated by Django 5.2 on 2026-09-13 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_alter_ogetaskgrammaticeight_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task9Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orthogram_id', models.CharField(db_index=True, max_length=10)),
                ('range_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_words', models.IntegerField(default=0)),
                ('chosen_count', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task9_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task9AttemptWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('chosen_letter', models.CharField(blank=True, max_length=10, null=True)),
                ('correct_letter', models.CharField(max_length=10)),
                ('is_correct', models.BooleanField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='main.task9attempt')),
            ],
        ),
        migrations.CreateModel(
            name='Task9WordStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orthogram_id', models.CharField(max_length=10)),
                ('range_code', models.CharField(max_length=10)),
                ('word', models.CharField(max_length=100)),
                ('correct_letter', models.CharField(max_length=10)),
                ('attempts', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('last_result', models.BooleanField(blank=True, null=True)),
                ('last_chosen_letter', models.CharField(blank=True, max_length=10, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('in_correction', models.BooleanField(default=False)),
                ('correction_since', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task9_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-correction_since'],
                'unique_together': {('user', 'orthogram_id', 'word')},
            },
        ),
    ]
