# Generated by Django 5.2 on 2026-09-16 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_task9attempt_task9attemptword_task9wordstat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckpointAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_code', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('error_count', models.PositiveSmallIntegerField(default=0)),
                ('passed', models.BooleanField(db_index=True, default=False)),
                ('answers_data', models.JSONField(blank=True, default=dict)),
                ('results_data', models.JSONField(blank=True, default=dict)),
                ('words_data', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'checkpoint_code', '-created_at'], name='main_checkp_user_id_5da2d3_idx')],
            },
        ),
    ]
