# Generated by Django 5.2 on 2026-09-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_checkpointattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointattempt',
            name='total_tasks',
            field=models.PositiveSmallIntegerField(default=9),
        ),
    ]
