# Generated by Django 5.2 on 2026-09-17 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_checkpointattempt_total_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('contact', models.CharField(max_length=100, verbose_name='Телефон или MAX')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='Откуда заявка')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callback_requests', to='main.diagnosticattempt', verbose_name='Диагностика')),
            ],
            options={
                'verbose_name': 'Заявка на звонок',
                'verbose_name_plural': 'Заявки на звонок',
                'ordering': ['-created_at'],
            },
        ),
    ]
