# Generated by Django 5.2 on 2026-09-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_callbackrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointattempt',
            name='digest',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='checkpointattempt',
            name='test_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
