# Generated by Django 5.2 on 2026-09-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_checkpointattempt_digest_checkpointattempt_test_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticattempt',
            name='answers_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Хэш ответов (защита от дублей)'),
        ),
    ]
