# Generated by Django 5.2 on 2026-10-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_diagnosticattempt_answers_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('grade', models.PositiveSmallIntegerField(default=7, verbose_name='Класс')),
                ('text', models.TextField(help_text='Пропуски: (а,о) — буквы через запятую; [х ,] — знаки (х = знака нет, пустой вариант = запятая).', verbose_name='Текст диктанта')),
                ('answers', models.TextField(blank=True, help_text='Правильный токен для каждого слота по порядку через | . Пример: и|х|,|ъ|/|тьс. Пусто = проверка недоступна.', verbose_name='Ключи ответов')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Источник/автор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Диктант',
                'verbose_name_plural': 'Диктанты',
                'ordering': ['grade', 'title'],
            },
        ),
    ]
