# Generated by Django 5.2 on 2026-10-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_dictationtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictationtask',
            name='answers',
            field=models.TextField(blank=True, help_text='Правильный токен для каждого слота по порядку, ПО ОДНОМУ В СТРОКУ. Пример: и / х / , / ъ (каждый с новой строки). Пусто = проверка недоступна.', verbose_name='Ключи ответов'),
        ),
        migrations.AlterField(
            model_name='dictationtask',
            name='source',
            field=models.CharField(blank=True, help_text='Вторая строка в карточке списка, например: «Контрольный диктант (повторение изученного в 5-6 кл.)». Пусто — подзаголовка нет.', max_length=200, verbose_name='Тип работы (подзаголовок)'),
        ),
    ]
