# Generated by Django 5.2 on 2026-10-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_alter_dictationtask_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackrequest',
            name='comment',
            field=models.TextField(blank=True, help_text='Класс, сроки, цель — что ученик сообщил о себе', verbose_name='Комментарий'),
        ),
    ]
